def compile(pattern: str) -> Pattern: ...
def findall(pattern: str, string: str) -> list[str]: ...
def fullmatch(pattern: str, string: str) -> Match: ...

class Pattern:
    def match(self, pattern: str, string: str) -> Match | None: ...
    def findall(self, pattern: str, string: str) -> list[str]: ...

class Match:
    pos: int
    endpos: int
    def groups(self) -> tuple[str, ...]: ...
